name: Show Event Info

on:
  push:
    branches:
      - feature-test

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
    - name: show event log
      run: |
      echo "Workflow triggered by: ${{github.actor}}"
      echo "Commit message: ${{github.event.head_commit.message}}"
      echo "Branch: ${{github.ref_name}}"
      echo  "Workflow Completed Successfully"